# Generated by Django 3.1.1 on 2021-12-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('0', 'manager'), ('1', 'recruiter'), ('2', 'developer')], default='2', max_length=10),
        ),
    ]
