# Generated by Django 3.1.1 on 2022-01-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211203_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('0', 'manager'), ('1', 'recruiter'), ('2', 'developer')], default='1', max_length=10),
        ),
    ]
