# Generated by Django 3.1.1 on 2021-12-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en-uk', 'English (uk)'), ('en-us', 'English (usa)')], default='fr', max_length=10),
        ),
    ]
