# Generated by Django 3.1.1 on 2022-01-03 09:10

import candidat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='resume',
            field=models.FileField(blank=True, upload_to=candidat.models.Candidates.get_upload_path),
        ),
    ]
