# Generated by Django 3.1.1 on 2022-01-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidat', '0002_candidates_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='resume',
            field=models.FileField(blank=True, upload_to='candidates/'),
        ),
    ]
