# Generated by Django 3.1.1 on 2021-12-31 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mission.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('job_description', models.FileField(blank=True, upload_to=mission.models.Mission.get_upload_path)),
                ('prime', models.CharField(choices=[('0', 'Pending'), ('1', 'Awarded'), ('2', 'Not Awarded')], default='0', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
